apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: front-end
          image: 955857785733.dkr.ecr.eu-central-1.amazonaws.com/docker_frontend:docker_frontend_image
          ports:
            - containerPort: 8080
  